version: "3"
services:
 web:
  build: 
   context: .
  command: bundle exec puma -C config/puma.rb
  volumes:
  - .:/webapp
  depends_on:
   - db
 db:
  image: mysql:5.7
  ports: 
  - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_USER: root
  volumes:
  - ./mysql_data:/var/lib/mysql
 nginx: 
  build:
   context: containers/nginx
  ports: 
  - 80:80
  volumes:
  - .:/webapp
  depends_on:
  - web

